# Generated by Django 4.1 on 2022-08-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='heartrate',
            field=models.IntegerField(default=72),
        ),
    ]
